### ISSUE TITLE
Modernize

### ISSUE THREAD

**Issue by vylmen** [ProtonMail/proton-python-client#10]
Hi,

I think this is critical:
* Use setuptools not distutils in setup.py
* python 2 is dead, buried and rotting
** so can ditch six

Opinion:
* PEP8 is nice, black is better
* use setup.cfg and a lean setup.py
* add annotations

I'm happy to implement if agreed.

**Comment by calexandru2018** [comment]
Migrated to setuptools and ditched python 2.x support. See #15
