### ISSUE TITLE
Managing email through API

### ISSUE THREAD

**Issue by delcroip** [ProtonMail/proton-python-client#30]
Hi,

is there any plan to allow email management through the API ?  
if it can use the same syntax as imaplib that would be perfect

where an API doc can be found ? I only found this one https://pastebin.com/LCMFGD1G, is it the latest ?

br

**Comment by calexandru2018** [comment]
Hey @delcroip 

It is not possible to so that due to the fact that 2FA is not yet fully implemented. Once 2fa is fully implemented, once can get full access to a account. Also, as of the moment, there are no official plans to make it work with the email API.

**Comment by bartbutler** [comment]
@delcroip you are probably looking for this: https://github.com/ProtonMail/proton-bridge

**Comment by delcroip** [comment]
> 
> 
> @delcroip you are probably looking for this: https://github.com/ProtonMail/proton-bridge

thank you but I am actually using it and I am looking for a solution that could directly interact with protonmail to implement my auto-forward (I feel that it is not the most efficient to use 2 services when one can be enough)

**Comment by delcroip** [comment]
> 
> 
> Hey @delcroip
> 
> It is not possible to so that due to the fact that 2FA is not yet fully implemented. Once 2fa is fully implemented, then you could get full access to your account. Although, as of the moment, there are no official plans to make it work with the email API.

Thank you, should I close that ticket then ?

**Comment by bartbutler** [comment]
> > @delcroip you are probably looking for this: https://github.com/ProtonMail/proton-bridge
> 
> thank you but I am actually using it and I am looking for a solution that could directly interact with protonmail to implement my auto-forward (I feel that it is not the most efficient to use 2 services when one can be enough)

I find it unlikely that that it will be easier to do this directly with the API, as you'll have to implement all the decryption operations yourself. Using the bridge and something off the shelf that speaks IMAP is probably going to be the easiest solution by far.
