### ISSUE TITLE
PyPI package is outdated

### ISSUE THREAD

**Issue by alexandrevicenzi** [ProtonMail/proton-python-client#33]
The latest version in https://pypi.org/project/proton-client/ is 0.4.1, but the current version released is 0.5.1.

Is there a plan to update PyPI?

**Comment by calexandru2018** [comment]
Hey @alexandrevicenzi 

Yes this should be update. @kaplun

**Comment by kaplun** [comment]
Yup! Updated!

**Comment by bmwilly** [comment]
Now the most recent versions on Github and PyPI are 0.7.1 and 0.5.1, respectively. Is there any plan for an automated publishing pipeline?
