### ISSUE TITLE
Email API Documentation?

### ISSUE THREAD

**Issue by chrisspen** [ProtonMail/proton-python-client#40]
Is there any documentation for actually using this API for sending and receiving emails?

The README just explains how to authenticate and store your authentication, and nothing else. Why authenticate if there's no functionality to authenticate for?

**Comment by bartbutler** [comment]
This is used as a component in the ProtonVPN Linux client and other small projects that need API authentication but is not intended to be a generic Proton CLI. Specifically for email, there is a tremendous amount of client-side logic and encryption that needs to be implemented to use the email API and we don't expect third parties to do this. If you'd like to send emails programmatically with a standard SMTP interface, I suggest you look at the Bridge project.

https://github.com/ProtonMail/proton-bridge
