### ISSUE TITLE
How do I decrypt an email

### ISSUE THREAD

**Issue by Anwenya** [ProtonMail/proton-python-client#48]
I've got my email. How do I decrypt it?

**Comment by JoshuaSamuelNichols** [comment]
Decrypting a Proton email requires the decryption key from the sender.

**To encrypt:** there is an option using the **External encryption**🔒button next to the 🗑️delete button. 
**Hotkey:** _Ctrl+Shift+E_ 

![image](https://github.com/ProtonMail/proton-python-client/assets/122940415/770b0e02-54b1-4908-b5b7-b0fa859fa775)

**Comment by Anwenya** [comment]
i already know how to do that,  still thank you

**Comment by twintersx** [comment]
I'd like to find out how to decrypt/decode an email body. 
I'm able to retrieve the email body with this:
"""
from proton.api import Session
import os 
import pprint 
import base64


cwd = os.getcwd()
__allow_alternative_routing__= True

proton_session = Session(
    'https://api.protonmail.ch',
    os.path.join(cwd, "logs"),
    os.path.join(cwd, "cache"),
    tls_pinning=False,
)

proton_session.enable_alternative_routing = True
proton_session.authenticate(username= "myemail@proton.me", password ="password")

def getMails():
   info_response = proton_session.api_request("/mail/v4/conversations")
   for conversation in info_response['Conversations']:
        get_email_id = conversation['ID']
        get_email_content = proton_session.api_request("/mail/v4/conversations/" + get_email_id)
        messages = get_email_content['Messages']
        email = messages[0]
        body = email['Body']
        
        # This line is not decoding correctly.. 
        decoded_body = base64.b64decode(body).decode('utf-8')

        pprint.pprint(decoded_body)

getMails()
"""

But the message is still encrypted I believe. Output example:
> '�`��\t`R%�i50����g����q\x137\x17�/��؍Up|5��8��)��\x0c'
